const ARGS = {
  A: 0x0,
  B: 0x1,
  C: 0x2,
  D: 0x3,
  ZERO: 0x4,
  BYTE: 0x5
};

const INSTRUCTIONS = [
  "adc", "add", "and", "dec", "exp", "hlt", "inc", "jc",
  "jmp", "jnc", "jno", "jns", "jnz", "jo", "js", "jz",
  "ld", "ldi", "mov", "neg", "not", "or", "rcl", "rcr",
  "rnd", "sar", "sbb", "shl", "shr", "st", "sub", "xor"
];

const REGISTERS = ["a", "b", "c", "d"];

const KEYWORDS = ["db", "equ"];

const OPERATORS = ["+", "-"];

const COMMANDS = [
  ["mov", [ARGS.A, ARGS.ZERO], 0x00],
  ["mov", [ARGS.A, ARGS.B], 0x01],
  ["mov", [ARGS.A, ARGS.C], 0x02],
  ["mov", [ARGS.A, ARGS.D], 0x03],
  ["mov", [ARGS.A, ARGS.ZERO], 0x04],
  ["mov", [ARGS.B, ARGS.A], 0x05],
  ["mov", [ARGS.C, ARGS.A], 0x06],
  ["mov", [ARGS.D, ARGS.A], 0x07],
  ["and", [ARGS.A, ARGS.ZERO], 0x08],
  ["and", [ARGS.A, ARGS.B], 0x09],
  ["and", [ARGS.A, ARGS.C], 0x0A],
  ["and", [ARGS.A, ARGS.D], 0x0B],
  ["and", [ARGS.A, ARGS.ZERO], 0x0C],
  ["and", [ARGS.B, ARGS.A], 0x0D],
  ["and", [ARGS.C, ARGS.A], 0x0E],
  ["and", [ARGS.D, ARGS.A], 0x0F],

  ["or", [ARGS.A, ARGS.ZERO], 0x10],
  ["or", [ARGS.A, ARGS.B], 0x11],
  ["or", [ARGS.A, ARGS.C], 0x12],
  ["or", [ARGS.A, ARGS.D], 0x13],
  ["or", [ARGS.A, ARGS.ZERO], 0x14],
  ["or", [ARGS.B, ARGS.A], 0x15],
  ["or", [ARGS.C, ARGS.A], 0x16],
  ["or", [ARGS.D, ARGS.A], 0x17],
  ["xor", [ARGS.A, ARGS.ZERO], 0x18],
  ["xor", [ARGS.A, ARGS.B], 0x19],
  ["xor", [ARGS.A, ARGS.C], 0x1A],
  ["xor", [ARGS.A, ARGS.D], 0x1B],
  ["xor", [ARGS.A, ARGS.ZERO], 0x1C],
  ["xor", [ARGS.B, ARGS.A], 0x1D],
  ["xor", [ARGS.C, ARGS.A], 0x1E],
  ["xor", [ARGS.D, ARGS.A], 0x1F],

  ["add", [ARGS.A, ARGS.ZERO], 0x20],
  ["add", [ARGS.A, ARGS.B], 0x21],
  ["add", [ARGS.A, ARGS.C], 0x22],
  ["add", [ARGS.A, ARGS.D], 0x23],
  ["add", [ARGS.A, ARGS.ZERO], 0x24],
  ["add", [ARGS.B, ARGS.A], 0x25],
  ["add", [ARGS.C, ARGS.A], 0x26],
  ["add", [ARGS.D, ARGS.A], 0x27],
  ["adc", [ARGS.A, ARGS.ZERO], 0x28],
  ["adc", [ARGS.A, ARGS.B], 0x29],
  ["adc", [ARGS.A, ARGS.C], 0x2A],
  ["adc", [ARGS.A, ARGS.D], 0x2B],
  ["adc", [ARGS.A, ARGS.ZERO], 0x2C],
  ["adc", [ARGS.B, ARGS.A], 0x2D],
  ["adc", [ARGS.C, ARGS.A], 0x2E],
  ["adc", [ARGS.D, ARGS.A], 0x2F],

  ["sub", [ARGS.A, ARGS.ZERO], 0x30],
  ["sub", [ARGS.A, ARGS.B], 0x31],
  ["sub", [ARGS.A, ARGS.C], 0x32],
  ["sub", [ARGS.A, ARGS.D], 0x33],
  ["sub", [ARGS.A, ARGS.ZERO], 0x34],
  ["sub", [ARGS.B, ARGS.A], 0x35],
  ["sub", [ARGS.C, ARGS.A], 0x36],
  ["sub", [ARGS.D, ARGS.A], 0x37],
  ["sbb", [ARGS.A, ARGS.ZERO], 0x38],
  ["sbb", [ARGS.A, ARGS.B], 0x39],
  ["sbb", [ARGS.A, ARGS.C], 0x3A],
  ["sbb", [ARGS.A, ARGS.D], 0x3B],
  ["sbb", [ARGS.A, ARGS.ZERO], 0x3C],
  ["sbb", [ARGS.B, ARGS.A], 0x3D],
  ["sbb", [ARGS.C, ARGS.A], 0x3E],
  ["sbb", [ARGS.D, ARGS.A], 0x3F],

  ["not", [ARGS.A], 0x40],
  ["not", [ARGS.B], 0x41],
  ["not", [ARGS.C], 0x42],
  ["not", [ARGS.D], 0x43],
  ["neg", [ARGS.A], 0x44],
  ["neg", [ARGS.B], 0x45],
  ["neg", [ARGS.C], 0x46],
  ["neg", [ARGS.D], 0x47],
  ["inc", [ARGS.A], 0x48],
  ["inc", [ARGS.B], 0x49],
  ["inc", [ARGS.C], 0x4A],
  ["inc", [ARGS.D], 0x4B],
  ["dec", [ARGS.A], 0x4C],
  ["dec", [ARGS.B], 0x4D],
  ["dec", [ARGS.C], 0x4E],
  ["dec", [ARGS.D], 0x4F],

  ["shl", [ARGS.A], 0x50],
  ["shl", [ARGS.B], 0x51],
  ["shl", [ARGS.C], 0x52],
  ["shl", [ARGS.D], 0x53],
  ["shr", [ARGS.A], 0x54],
  ["shr", [ARGS.B], 0x55],
  ["shr", [ARGS.C], 0x56],
  ["shr", [ARGS.D], 0x57],
  ["sar", [ARGS.A], 0x58],
  ["sar", [ARGS.B], 0x59],
  ["sar", [ARGS.C], 0x5A],
  ["sar", [ARGS.D], 0x5B],
  ["exp", [ARGS.A], 0x5C],
  ["exp", [ARGS.B], 0x5D],
  ["exp", [ARGS.C], 0x5E],
  ["exp", [ARGS.D], 0x5F],

  ["rcl", [ARGS.A], 0x60],
  ["rcl", [ARGS.B], 0x61],
  ["rcl", [ARGS.C], 0x62],
  ["rcl", [ARGS.D], 0x63],
  ["rcr", [ARGS.A], 0x64],
  ["rcr", [ARGS.B], 0x65],
  ["rcr", [ARGS.C], 0x66],
  ["rcr", [ARGS.D], 0x67],

  ["ld", [ARGS.A, ARGS.BYTE], 0x80],
  ["ld", [ARGS.B, ARGS.BYTE], 0x81],
  ["ld", [ARGS.C, ARGS.BYTE], 0x82],
  ["ld", [ARGS.D, ARGS.BYTE], 0x83],
  ["ld", [ARGS.A, ARGS.BYTE], 0x84],
  ["ld", [ARGS.B, ARGS.BYTE], 0x85],
  ["ld", [ARGS.C, ARGS.BYTE], 0x86],
  ["ld", [ARGS.D, ARGS.BYTE], 0x87],
  ["ldi", [ARGS.A, ARGS.BYTE], 0x88],
  ["ldi", [ARGS.B, ARGS.BYTE], 0x89],
  ["ldi", [ARGS.C, ARGS.BYTE], 0x8A],
  ["ldi", [ARGS.D, ARGS.BYTE], 0x8B],
  ["ldi", [ARGS.A, ARGS.BYTE], 0x8C],
  ["ldi", [ARGS.B, ARGS.BYTE], 0x8D],
  ["ldi", [ARGS.C, ARGS.BYTE], 0x8E],
  ["ldi", [ARGS.D, ARGS.BYTE], 0x8F],

  ["ld", [ARGS.A, ARGS.A], 0x90],
  ["ld", [ARGS.B, ARGS.A], 0x91],
  ["ld", [ARGS.C, ARGS.A], 0x92],
  ["ld", [ARGS.D, ARGS.A], 0x93],
  ["ld", [ARGS.A, ARGS.B], 0x94],
  ["ld", [ARGS.B, ARGS.B], 0x95],
  ["ld", [ARGS.C, ARGS.B], 0x96],
  ["ld", [ARGS.D, ARGS.B], 0x97],
  ["ld", [ARGS.A, ARGS.C], 0x98],
  ["ld", [ARGS.B, ARGS.C], 0x99],
  ["ld", [ARGS.C, ARGS.C], 0x9A],
  ["ld", [ARGS.D, ARGS.C], 0x9B],
  ["ld", [ARGS.A, ARGS.D], 0x9C],
  ["ld", [ARGS.B, ARGS.D], 0x9D],
  ["ld", [ARGS.C, ARGS.D], 0x9E],
  ["ld", [ARGS.D, ARGS.D], 0x9F],

  ["st", [ARGS.A, ARGS.BYTE], 0xA0],
  ["st", [ARGS.B, ARGS.BYTE], 0xA1],
  ["st", [ARGS.C, ARGS.BYTE], 0xA2],
  ["st", [ARGS.D, ARGS.BYTE], 0xA3],
  ["st", [ARGS.A, ARGS.BYTE], 0xA4],
  ["st", [ARGS.B, ARGS.BYTE], 0xA5],
  ["st", [ARGS.C, ARGS.BYTE], 0xA6],
  ["st", [ARGS.D, ARGS.BYTE], 0xA7],
  ["rnd", [ARGS.A], 0xA8],
  ["rnd", [ARGS.B], 0xA9],
  ["rnd", [ARGS.C], 0xAA],
  ["rnd", [ARGS.D], 0xAB],
  ["rnd", [ARGS.A], 0xAC],
  ["rnd", [ARGS.B], 0xAD],
  ["rnd", [ARGS.C], 0xAE],
  ["rnd", [ARGS.D], 0xAF],

  ["st", [ARGS.A, ARGS.A], 0xB0],
  ["st", [ARGS.B, ARGS.A], 0xB1],
  ["st", [ARGS.C, ARGS.A], 0xB2],
  ["st", [ARGS.D, ARGS.A], 0xB3],
  ["st", [ARGS.A, ARGS.B], 0xB4],
  ["st", [ARGS.B, ARGS.B], 0xB5],
  ["st", [ARGS.C, ARGS.B], 0xB6],
  ["st", [ARGS.D, ARGS.B], 0xB7],
  ["st", [ARGS.A, ARGS.C], 0xB8],
  ["st", [ARGS.B, ARGS.C], 0xB9],
  ["st", [ARGS.C, ARGS.C], 0xBA],
  ["st", [ARGS.D, ARGS.C], 0xBB],
  ["st", [ARGS.A, ARGS.D], 0xBC],
  ["st", [ARGS.B, ARGS.D], 0xBD],
  ["st", [ARGS.C, ARGS.D], 0xBE],
  ["st", [ARGS.D, ARGS.D], 0xBF],

  ["jz", [ARGS.A], 0xC0],
  ["jc", [ARGS.A], 0xC1],
  ["js", [ARGS.A], 0xC2],
  ["jo", [ARGS.A], 0xC3],
  ["jz", [ARGS.B], 0xC4],
  ["jc", [ARGS.B], 0xC5],
  ["js", [ARGS.B], 0xC6],
  ["jo", [ARGS.B], 0xC7],
  ["jz", [ARGS.C], 0xC8],
  ["jc", [ARGS.C], 0xC9],
  ["js", [ARGS.C], 0xCA],
  ["jo", [ARGS.C], 0xCB],
  ["jz", [ARGS.D], 0xCC],
  ["jc", [ARGS.D], 0xCD],
  ["js", [ARGS.D], 0xCE],
  ["jo", [ARGS.D], 0xCF],

  ["jnz", [ARGS.A], 0xD0],
  ["jnc", [ARGS.A], 0xD1],
  ["jns", [ARGS.A], 0xD2],
  ["jno", [ARGS.A], 0xD3],
  ["jnz", [ARGS.B], 0xD4],
  ["jnc", [ARGS.B], 0xD5],
  ["jns", [ARGS.B], 0xD6],
  ["jno", [ARGS.B], 0xD7],
  ["jnz", [ARGS.C], 0xD8],
  ["jnc", [ARGS.C], 0xD9],
  ["jns", [ARGS.C], 0xDA],
  ["jno", [ARGS.C], 0xDB],
  ["jnz", [ARGS.D], 0xDC],
  ["jnc", [ARGS.D], 0xDD],
  ["jns", [ARGS.D], 0xDE],
  ["jno", [ARGS.D], 0xDF],

  ["jz", [ARGS.BYTE], 0xE0],
  ["jc", [ARGS.BYTE], 0xE1],
  ["js", [ARGS.BYTE], 0xE2],
  ["jo", [ARGS.BYTE], 0xE3],
  ["jnz", [ARGS.BYTE], 0xE4],
  ["jnc", [ARGS.BYTE], 0xE5],
  ["jns", [ARGS.BYTE], 0xE6],
  ["jno", [ARGS.BYTE], 0xE7],
  ["jmp", [ARGS.BYTE], 0xE8],
  ["jmp", [ARGS.BYTE], 0xE9],
  ["jmp", [ARGS.BYTE], 0xEA],
  ["jmp", [ARGS.BYTE], 0xEB],
  ["hlt", [], 0xEC],
  ["hlt", [], 0xED],
  ["hlt", [], 0xEE],
  ["hlt", [], 0xEF],

  ["jmp", [ARGS.A], 0xF0],
  ["jmp", [ARGS.A], 0xF1],
  ["jmp", [ARGS.A], 0xF2],
  ["jmp", [ARGS.A], 0xF3],
  ["jmp", [ARGS.B], 0xF4],
  ["jmp", [ARGS.B], 0xF5],
  ["jmp", [ARGS.B], 0xF6],
  ["jmp", [ARGS.B], 0xF7],
  ["jmp", [ARGS.C], 0xF8],
  ["jmp", [ARGS.C], 0xF9],
  ["jmp", [ARGS.C], 0xFA],
  ["jmp", [ARGS.C], 0xFB],
  ["jmp", [ARGS.D], 0xFC],
  ["jmp", [ARGS.D], 0xFD],
  ["jmp", [ARGS.D], 0xFE],
  ["jmp", [ARGS.D], 0xFF],
];

module.exports = {
  ARGS, INSTRUCTIONS, REGISTERS, KEYWORDS, OPERATORS, COMMANDS
}